# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-07 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_tolauser_activecountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='name',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Record name'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='url',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Link to file or folder'),
        ),
    ]
